@startuml

state "Sorting and searching" as Sorting
state "Data structure" as DS
state "Recursion" as Recursion
state "Java" as Java

[*] --> Sorting
Sorting : B1: 5 msg. (CQ, CSO, DH, DH, DH) - 7 min
Sorting --> DS : P1: 21,3 h
DS : B2: 2 msg. (CS, CS) - 0,9 min
DS --> Recursion : P2: 3,2 h
Recursion : B3: 1 msg. (CQ) - 0 min
Recursion --> Java : P3: 14,7 h
Java : B4: 2 msg. (CQ, CQ) - 1,3 min
Java --> DS : P4: 1,4 h
DS : B5: 2 msg. (CQ, CQ) - 1,3 min

@enduml