@startmindmap

* Metacognition Mode of Flavel
** Metacognitive knowledge
*** Person
**** Understanding of their beliefs, \n strengths, and weaknesses

*** Task
**** Understanding the degree of \n difficulty

*** Strategy
**** Understanding strategies that can \n help, such as the use of mnemonics, \n organizing information, and/or \n repetition

** Metacognitive experiences
*** Reflections
**** Whether things are going well or \n if something needs to be adjusted

*** Feelings of confidence or uncertainty
**** The person may feel that they are \n understanding a task well or, on the \n contrary, may realize they are \n struggling. These experiences can \n serve as indicators for the person to \n adjust their cognitive strategies while \n performing a task.

** Goals (or tasks)
*** Goal setting is a crucial part of the \n cognitive regulation process, as it \n defines what the person wants to \n achieve and influences the selection \n of strategies to be used.

** Actions (or strategies)
*** Planning
**** Establishing a plan to tackle a \n task, such as dividing a text into \n sections to facilitate understanding.

*** Monitoring
**** Checking if one is understanding \n an explanation

*** Evaluation
**** Reflecting on performance after \n completing a task, evaluating what \n was done 
@endmindmap
