@startmindmap

* Modelo de Flavel
** Conhecimento meta cognitivo
*** Pessoa
**** Compreensão sobre suas crenças, forças \n e fraquezas

*** Tarefa
**** Entendimento sobre o grau da dificuldade

*** Estratégia
**** Entendimento sobre sobre as estratégias \n que podem facilitar como o uso de \n mnemônicos, organização de informações \n e\ou repetição

** Experiências meta cognitivas
*** Reflexões
**** Se está indo bem, ou se precisa \n ajustar alguma coisa

*** Sentimentos de confiança ou incerteza
**** A pessoa pode sentir que está \n compreendendo bem uma tarefa ou, pelo \n contrário, pode perceber que está com \n dificuldades. Essas experiências podem \n servir de indicadores para a pessoa \n ajustar suas estratégias cognitivas enquanto \n realiza uma tarefa.

** Objetivos (ou tarefas)
*** A definição de objetivos é uma parte crucial \n do processo de regulação cognitiva, pois \n define o que a pessoa deseja alcançar \n e influencia a seleção das estratégias \n que serão usadas.

** Ações (ou estratégias)
*** Planejamento
**** Estabelecer um plano para abordar uma \n tarefa, como dividir um texto em seções \n para facilitar o entendimento.

*** Monitoramento
**** Verificar se está entendendo uma \n explicação

*** Avaliação
**** Refletir sobre o desempenho após a \n conclusão da tarefa, avaliando o que foi feito

@endmindmap
